@host = http://localhost
@port = 5252
@Restaurants.API_HostAddress = http://localhost:5252
@token = CfDJ8Oqj69flhYtOkYhVNrXQ30m-QRxzjflz6iJy8HEvVJ3Txlvjd_QssJ3LJ8HA-gqIXekZ_wgPOEq1SRQQ8z2Zw2AfZYI7OhuxmYp3IBNTZcXmR4yZCiaENTySy-szcUztbV9H2U8jTHlqceaTOgNPX0yHF48oJP4lBhPe-tMdUTlxi002IKwJOqWiKdsIEPSPJoKCw9r9gDZp_xFwFN5BEenEH6n60K2-BWGhpE0uLC7p17cLk6zkAoynMtcvC9YBXnPfHSdgqwVVrEP1lsmPQhenlrNVvOxDL-hxBykohDr1JP5tfftdLZkFcEIG1s5LnT21GhwUHAay7_eFV-iQKH1rOHBKl8v7BHnGmWnYtLMkD-7fr8hycw-e6jL8AeIA-46QeGlqp-oPvTcC9LVsDH52XFjiF8I7gdK2T9P4abjmsfA6DrS5SB-jXcU9wdVRiE5p9FoUFRCPbYaQm-ZE6hKJofuLP87qGd48_76sx3ZZWI44j4MbdEtfeGRpEi9CpWq6mMuGysslJ9JA8bZG8tEBgsBXm_MYd0NSJ3HnZ8IkUOtI0OuzODcSLIddMFwxHlvea0YUMIcL2MzCerdZAgjhuYFydthWDtCvZ_W1dlsxWbOVG_w5yS3W2_u4IO8aUHDo1kyOzIpEkn3gn-0Mt35IaKxAPl5vUOovvSHgpk9WJEsZJJlLadQ_kCIqRdALziCqQw9E2pGRnPnSMoow7dkKfh_50VaICm_R4RAbqTklZNcJkmtb9j83P9bQD1DtQR0zIUIvkvcJrWLV8BHEYvE_o__S2r4BIrgdjJiMYbLz0orcH3Pc-LduthS410zU7Q2__7cm6A2EPly0xqIXHDI96lYNgpimcBzfyTD6EZrveo4LACMdaKpxI3sGjsjMYg

GET {{Restaurants.API_HostAddress}}/api/restaurants
# Authorization: Bearer {{token}}
###

@id=8
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}
Authorization: Bearer {{token}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json
# Authorization: Bearer {{token}}
{
  "Name": "Owner Restaurant",
  "Description": "A new restaurant description",
  "Category": "rapida",
  "HasDelivery": true,
  "ContactEmail": "test@gmail.com",
  "ContactNumber": "123456789",
  "City": "New York",
  "Street": "123 Main St",
  "PostalCode": "10-001"
}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}
Authorization: Bearer {{token}}

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "Name": "Update Restaurant",
  "Description": "Test Update",
  "HasDelivery": false
}

###

@restaurantId=12
POST {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes
Content-Type: application/json

{
  "Name": "New Dishtest",
  "Description": "A new dish description",
  "Price": 9,
  "KiloCalories": 500
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes
Authorization: Bearer {{token}}

###

@dishId=6
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes/{{dishId}}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes/{{dishId}}

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json
{
  "email": "owner@gmail.com",
  "password": "Abc12345@"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json
# "email": "test@gmail.com",
# "email": "admin@gmail.com",
# "email": "user@gmail.com",
# "email": "owner@gmail.com",
{
  "email": "owner@gmail.com",
  "password": "Abc12345@"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "userEmail": "test@gmail.com",
  "roleName": "User"
}

###

PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Nationality": "French",
  "DateOfBirth": "2010-06-01"
}

###
