@host = http://localhost
@port = 5252
@Restaurants.API_HostAddress = http://localhost:5252

GET {{Restaurants.API_HostAddress}}/api/restaurants

###

@id=12
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json
{
  "Name": "New Restaurant",
  "Description": "A new restaurant description",
  "Category": "",
  "HasDelivery": true,
  "ContactEmail": "testgmail.com",
  "ContactNumber": "123456789",
  "City": "New York",
  "Street": "123 Main St",
  "PostalCode": "10001"
}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}
Content-Type: application/json
{
  "Name": "Test",
  "Description": "Test Update",
  "HasDelivery": false
}

###

@restaurantId=12
POST {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes
Content-Type: application/json

{
  "Name": "New Dishtest",
  "Description": "A new dish description",
  "Price": 9,
  "KiloCalories": 500
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes

###

@dishId=6
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes/{{dishId}}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes/{{dishId}}

###
