@host = http://localhost
@port = 5252
@Restaurants.API_HostAddress = http://localhost:5252
@token = CfDJ8Oqj69flhYtOkYhVNrXQ30mMVnfaetvJRCjjBgdUuCWsk74z9kz7ufggzAcV-llFTB22BJw9H7LhJYNWOvkblSF5osLhj4xFhSFTidSXjOZKhnPErdcrU3hcgH-jdUfZia1OVZA68YSsiHn4qun6uhibKfPMV2WwISroB9aVSedzuH01GdaXAwA4jKZpeJ8gIK8BwV97KW0Ntr2-yKkai1ovstRcPNrxTagFeeNFVXgqHnzx-n_sJInK2q0vxVlP7Ponp25TgfRLOUR4qcMBme40d5qFivRxg3GK_WhLbvRLM6mHDtU1KpX869hEkyJ8PRMSiuVaSSToVZWOKvAyDuZwrEji-UPuthC6eeNx6Mibu5uwGVMLMIjj_kiRmkWx5WVe3ntVCFlZcSKUqJzkaWeMaEu1cWlSXliMux_qp7_pqSdzIONAur7hT7TnRZ5VLYg0GU6xorFjBl7WMLzqJu5KhlqvHVlC28eyrT9e5SoOneWSZRZpG1yV55fPL-tnYj0_u9ZV3nEZj4mEj7eURD8G6JrYZsdS472lBDWNaHv7A6mGmCmrh2xh8x4i8-ZH9GksiiNuVpZjG6_iMF9AWcOR6O_RHeT9r2F_UibWDjUgEnSLeHXmApioIBJ25ic6qHI8SXSLYC72YyvKtbp3rYY8WquzOpFVvxzt00WGg26bImGIzpDmAM-fWyFDnBQEu3cA3UPYnI1KP-XoU6tnrkiKrj5GM5ZmmoJlJo4hE3xrV-jn-YdDCaft56vX2bOEeOCA2vr7TNsUP5EHRafCfSWFRzx7t7syV6RDe2Hfliqj

GET {{Restaurants.API_HostAddress}}/api/restaurants
###

@id=12
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}
Authorization: Bearer {{token}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "Name": "New Restaurant2",
  "Description": "A new restaurant description",
  "Category": "rapida",
  "HasDelivery": true,
  "ContactEmail": "test@gmail.com",
  "ContactNumber": "123456789",
  "City": "New York",
  "Street": "123 Main St",
  "PostalCode": "10-001"
}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}
Content-Type: application/json
{
  "Name": "Test",
  "Description": "Test Update",
  "HasDelivery": false
}

###

@restaurantId=12
POST {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes
Content-Type: application/json

{
  "Name": "New Dishtest",
  "Description": "A new dish description",
  "Price": 9,
  "KiloCalories": 500
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes

###

@dishId=6
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes/{{dishId}}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes/{{dishId}}

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json
{
  "email": "owner@gmail.com",
  "password": "Abc12345@"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json
# "email": "test@gmail.com",
# "email": "admin@gmail.com",
# "email": "user@gmail.com",
# "email": "owner@gmail.com",
{
  "email": "owner@gmail.com",
  "password": "Abc12345@"
}

###

